#!/usr/bin/env bash
# new-demo-pr.sh — Create a throwaway pull request, fast.
#
# Usage:
#   ./new-demo-pr.sh                       # auto title, touches default demo (07-workflow-triggers)
#   ./new-demo-pr.sh "Custom title"        # custom PR title
#   ./new-demo-pr.sh -D 09-unit-testing    # target a specific demo folder
#   ./new-demo-pr.sh -D all                # touch every PR-triggered demo (fires them all)
#   ./new-demo-pr.sh -m                    # merge the PR after creating it
#   ./new-demo-pr.sh -d                    # draft PR
#   ./new-demo-pr.sh -b feature/x          # use a specific branch name
#
# Run it as many times as you want — every call generates a new branch,
# commit, and PR against `main` on the current `origin` remote.
#
# The PR modifies a file inside the target demo's folder so that any
# pull_request-triggered workflow scoped to `demos/<demo>/**` actually fires.
#
# Requires: git, gh (authenticated: `gh auth login`).

set -euo pipefail

cd "$(dirname "$0")"

MERGE=0
DRAFT=0
BRANCH=""
TITLE=""
DEMO="07-workflow-triggers"   # default target

# Demos that have pull_request-triggered workflows (kept in sync with deploy script)
PR_DEMOS=(
  07-workflow-triggers
  08-cicd-pipelines
  09-unit-testing
  10-matrix-builds
  11-parallel-jobs
  12-sequential-pipelines
  33-production-pipeline-concepts
  39-supply-chain-security
)

while (( $# )); do
  case "$1" in
    -m|--merge)  MERGE=1; shift ;;
    -d|--draft)  DRAFT=1; shift ;;
    -b|--branch) BRANCH="${2:?--branch needs a value}"; shift 2 ;;
    -D|--demo)   DEMO="${2:?--demo needs a value}"; shift 2 ;;
    -h|--help)   sed -n '2,20p' "$0"; exit 0 ;;
    *)           TITLE="$1"; shift ;;
  esac
done

# Pre-flight checks
command -v gh >/dev/null || { echo "gh CLI not found. Install: https://cli.github.com" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "gh not authenticated. Run: gh auth login" >&2; exit 1; }
git rev-parse --git-dir >/dev/null 2>&1 || { echo "not a git repo" >&2; exit 1; }

# Refuse to clobber uncommitted work
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "You have uncommitted changes. Commit or stash them first." >&2
  exit 1
fi

DEFAULT_BRANCH="$(gh repo view --json defaultBranchRef -q .defaultBranchRef.name 2>/dev/null || echo main)"
STAMP="$(date +%Y%m%d-%H%M%S)"
NONCE="$RANDOM"
BRANCH="${BRANCH:-demo/pr-${STAMP}-${NONCE}}"
TITLE="${TITLE:-Demo PR ${STAMP}}"

echo "→ syncing ${DEFAULT_BRANCH}"
git fetch origin "${DEFAULT_BRANCH}" --quiet
git checkout "${DEFAULT_BRANCH}" --quiet
git pull --ff-only origin "${DEFAULT_BRANCH}" --quiet

echo "→ creating branch ${BRANCH}"
git checkout -b "${BRANCH}" --quiet

# Make a trivial, traceable change inside the target demo folder so that
# pull_request-triggered workflows scoped to `demos/<demo>/**` fire.
if [[ "${DEMO}" == "all" ]]; then
  TARGETS=("${PR_DEMOS[@]}")
else
  if [[ ! -d "demos/${DEMO}" ]]; then
    echo "demos/${DEMO} not found. Available PR-triggered demos:" >&2
    printf '  %s\n' "${PR_DEMOS[@]}" >&2
    git checkout "${DEFAULT_BRANCH}" --quiet
    git branch -D "${BRANCH}" --quiet
    exit 1
  fi
  TARGETS=("${DEMO}")
fi

for d in "${TARGETS[@]}"; do
  LOG_DIR="demos/${d}/.demo-prs"
  LOG="${LOG_DIR}/history.md"
  mkdir -p "${LOG_DIR}"
  [[ -f "${LOG}" ]] || echo "# Demo PR history for ${d}" > "${LOG}"
  echo "- ${STAMP} \`${BRANCH}\` — ${TITLE}" >> "${LOG}"
  git add -f "${LOG}"
done

if git diff --cached --quiet; then
  echo "nothing staged after edit — aborting" >&2
  git checkout "${DEFAULT_BRANCH}" --quiet
  git branch -D "${BRANCH}" --quiet
  exit 1
fi
git commit -m "${TITLE}" --quiet

echo "→ pushing"
git push -u origin "${BRANCH}" --quiet

echo "→ opening PR"
PR_ARGS=(--base "${DEFAULT_BRANCH}" --head "${BRANCH}" --title "${TITLE}" \
         --body "Automated demo PR generated by new-demo-pr.sh on ${STAMP}.")
(( DRAFT )) && PR_ARGS+=(--draft)
PR_URL="$(gh pr create "${PR_ARGS[@]}")"
echo "PR: ${PR_URL}"

if (( MERGE )); then
  echo "→ merging (squash + delete branch)"
  gh pr merge --squash --delete-branch --auto "${PR_URL}"
fi

# Return to default branch so the next run starts clean
git checkout "${DEFAULT_BRANCH}" --quiet
