apiVersion: v1
kind: Service
metadata:
  name: devops-app-lb
  annotations:
    # Provision an internet-facing NLB
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector: { app: devops-app }
  ports:
    - port: 80
      targetPort: 8000
