apiVersion: v1
kind: Pod
metadata: { name: loadgen }
spec:
  restartPolicy: Never
  containers:
    - name: hey
      image: williamyeh/hey:latest
      args: ["-z", "120s", "-c", "50", "http://devops-app-svc/health"]
