apiVersion: v1
kind: Service
metadata:
  name: devops-app-svc
spec:
  type: ClusterIP                    # default; in-cluster only
  selector:
    app: devops-app                  # matches Pod labels
  ports:
    - name: http
      port: 80                       # service port
      targetPort: 8000               # container port
      protocol: TCP
