apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard            # kind default; in EKS use 'gp3' or 'gp2'
  resources:
    requests:
      storage: 10Mi
