apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      # Pull from private Artifactory (Demo 30)
      imagePullSecrets:
        - name: jfrog-pull-secret
      containers:
        - name: app
          image: devops-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: SECRET_KEY
          volumeMounts:
            - name: creds-dir
              mountPath: /etc/creds
              readOnly: true
      volumes:
        - name: creds-dir
          secret:
            secretName: app-creds
            items:
              - key: db.password
                path: db.password
                mode: 0400              # tighten file perms
