#!/usr/bin/env python3
"""Aggregate every demo's workflows into the repo-root .github/workflows/.

For each `demos/<demo>/.github/workflows/*.y(a)ml` we:
  1. Prefix `name:` with `[<demo>]` so jobs are easy to spot in the Actions UI.
  2. Inject `defaults.run.working-directory: demos/<demo>` so every `run:` step
     executes inside the demo's own folder (where its app.py / requirements.txt
     / Dockerfile / tests live).
  3. Force `on:` to `workflow_dispatch:` only by default (preserving any existing
     dispatch inputs). This way a single `git push` does not fire 20+ workflows;
     instructors demo each one on demand from the Actions tab.
     Pass --mode=push to additionally scope the original push trigger to
     `paths: ['demos/<demo>/**']`.
  4. Rewrite local action refs `uses: ./...` -> `uses: ./demos/<demo>/...`
  5. Write to `.github/workflows/<demo>__<original>.yaml` with a banner.

Run from the repo root:
    python3 tools/deploy_demo_workflows.py            # workflow_dispatch-only
    python3 tools/deploy_demo_workflows.py --mode=push  # also keep push triggers (scoped)
    python3 tools/deploy_demo_workflows.py --clean      # wipe generated files first
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required. Install with: pip install pyyaml")

REPO_ROOT = Path(__file__).resolve().parent.parent
DEMOS_DIR = REPO_ROOT / "demos"
DEST_DIR = REPO_ROOT / ".github" / "workflows"

GENERATED_MARKER = "# GENERATED by tools/deploy_demo_workflows.py — DO NOT EDIT.\n"


def normalize_on(on_value, demo_rel: str, mode: str) -> dict:
    """Return a dict-form `on:` block.

    Always includes `workflow_dispatch:` (preserving any existing inputs).
    In --mode=push, preserves push/pull_request triggers but scopes their
    `paths:` to the demo's folder so a push only fires its own workflows.
    In default mode, drops every other trigger.
    """
    # Normalise to a mapping
    if on_value is None:
        on_map: dict = {}
    elif isinstance(on_value, str):
        on_map = {on_value: None}
    elif isinstance(on_value, list):
        on_map = {k: None for k in on_value}
    elif isinstance(on_value, dict):
        on_map = dict(on_value)
    else:
        on_map = {}

    # Preserve any existing workflow_dispatch (with its inputs) or add an empty one.
    dispatch = on_map.get("workflow_dispatch")
    new_on: dict = {"workflow_dispatch": dispatch if dispatch is not None else {}}

    if mode == "push":
        path_filter = [f"demos/{demo_rel}/**", f".github/workflows/{demo_rel}__*"]
        for trig in ("push", "pull_request"):
            if trig in on_map:
                cfg = on_map[trig] or {}
                if not isinstance(cfg, dict):
                    cfg = {}
                cfg["paths"] = path_filter
                new_on[trig] = cfg
    return new_on


def rewrite_local_uses(node, demo_rel: str):
    """Walk the YAML tree, rewriting `uses: ./...` -> `uses: ./demos/<demo>/...`."""
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "uses" and isinstance(v, str) and v.startswith("./") and not v.startswith(f"./demos/"):
                node[k] = f"./demos/{demo_rel}/{v[2:]}"
            else:
                rewrite_local_uses(v, demo_rel)
    elif isinstance(node, list):
        for item in node:
            rewrite_local_uses(item, demo_rel)


def transform(workflow: dict, demo_rel: str, mode: str) -> dict:
    workflow = dict(workflow)  # shallow copy

    # 1. Prefix name
    original_name = workflow.get("name", demo_rel)
    workflow["name"] = f"[{demo_rel}] {original_name}"

    # 2. defaults.run.working-directory
    defaults = dict(workflow.get("defaults") or {})
    run_defaults = dict(defaults.get("run") or {})
    run_defaults.setdefault("working-directory", f"demos/{demo_rel}")
    defaults["run"] = run_defaults
    workflow["defaults"] = defaults

    # 3. on: triggers
    workflow["on"] = normalize_on(workflow.get("on") or workflow.get(True), demo_rel, mode)
    # PyYAML may parse the bareword `on` as the boolean True; remove that key.
    workflow.pop(True, None)

    # 4. rewrite local action refs
    rewrite_local_uses(workflow, demo_rel)

    return workflow


def find_workflow_files() -> list[tuple[str, Path]]:
    out: list[tuple[str, Path]] = []
    for demo_dir in sorted(p for p in DEMOS_DIR.iterdir() if p.is_dir()):
        wf_dir = demo_dir / ".github" / "workflows"
        if not wf_dir.is_dir():
            continue
        for wf in sorted(wf_dir.iterdir()):
            if wf.suffix in (".yml", ".yaml") and wf.is_file():
                out.append((demo_dir.name, wf))
    return out


def clean_generated() -> int:
    if not DEST_DIR.exists():
        return 0
    removed = 0
    for f in DEST_DIR.iterdir():
        if not f.is_file() or f.suffix not in (".yml", ".yaml"):
            continue
        head = f.read_text(errors="ignore").splitlines()[:1]
        if head and head[0].strip() == GENERATED_MARKER.strip():
            f.unlink()
            removed += 1
    return removed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--mode", choices=("dispatch", "push"), default="dispatch",
                    help="dispatch (default): only workflow_dispatch button. "
                         "push: also keep push/pull_request triggers scoped to the demo folder.")
    ap.add_argument("--clean", action="store_true",
                    help="Remove previously generated workflows before writing.")
    args = ap.parse_args()

    DEST_DIR.mkdir(parents=True, exist_ok=True)

    if args.clean:
        n = clean_generated()
        print(f"cleaned {n} generated workflow file(s)")

    files = find_workflow_files()
    if not files:
        print("No demo workflows found.")
        return 0

    written = 0
    for demo_name, src in files:
        try:
            data = yaml.safe_load(src.read_text())
        except yaml.YAMLError as e:
            print(f"  ! skip {src.relative_to(REPO_ROOT)}: invalid YAML: {e}", file=sys.stderr)
            continue
        if not isinstance(data, dict):
            print(f"  ! skip {src.relative_to(REPO_ROOT)}: not a mapping at top level", file=sys.stderr)
            continue

        transformed = transform(data, demo_name, args.mode)
        dest = DEST_DIR / f"{demo_name}__{src.stem}.yaml"

        body = yaml.safe_dump(transformed, sort_keys=False, default_flow_style=False, width=100)
        header = (
            GENERATED_MARKER
            + f"# Source: demos/{demo_name}/.github/workflows/{src.name}\n"
            + f"# Regenerate with: python3 tools/deploy_demo_workflows.py --clean --mode={args.mode}\n"
        )
        dest.write_text(header + body)
        written += 1
        print(f"  + {dest.relative_to(REPO_ROOT)}")

    print(f"\nWrote {written} workflow file(s) to {DEST_DIR.relative_to(REPO_ROOT)}")
    print("Commit and push to make them available in the Actions tab.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
